# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QAnnAGNPS
                                 A QGIS plugin
 This plugin facilitates the use of AnnAGNPS in the execution and in the visualization of the results.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-09
        copyright            : (C) 2023 by Iñigo Barberena
        email                : inigo.barberena@unavarra.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EphemeralGully class from file EphemeralGully.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qannagnps import qannagnps
    return qannagnps(iface)
